const mensajesSeguimiento = [
    "Hola 😊 ¿Cómo te sientes hoy? Me gustaría saber qué ha sido de ti hasta este momento 🌿✨",
    "¡Hola! 🌸 Espero que tu día esté yendo bien. ¿Cómo te encuentras hoy?",
    "Hey 👋 Hace un tiempo no sé de ti, ¿cómo va todo últimamente?",
    "Hola 🌞 Solo quería saludarte y saber cómo te ha ido estos días.",
    "¡Hola! 💬 Me alegra poder escribirte de nuevo. ¿Cómo te ha tratado la vida últimamente?",
    "Hola 🌿 Espero que estés teniendo un buen día. ¿Cómo te sientes hoy?",
    "¡Hola! 🌼 Hace un rato que no hablamos, quería saber cómo te encuentras.",
    "Hey ✨ ¿Todo bien contigo? Solo quería recordarte que estoy aquí si necesitas hablar.",
    "Hola 💫 ¿Cómo estás? Espero que hayas tenido momentos bonitos últimamente.",
    "¡Hola! 🌻 Me gustaría saber cómo te ha ido, ¿te gustaría contarme un poco?",
    "Hola 😊 ¿Cómo te ha tratado esta semana?",
    "Hola 🌈 Me alegra volver a saludarte, ¿cómo va tu día?",
    "¡Hola! 🌷 Espero que estés cuidándote mucho. ¿Cómo te sientes últimamente?",
    "Hey 🙌 Hace un tiempo que no conversamos, ¿cómo te ha ido desde la última vez?",
    "Hola 💭 He estado pensando en ti. ¿Cómo te encuentras hoy?",
    "Hola 🌞 Espero que tu día esté lleno de cosas buenas. ¿Cómo va todo?",
    "¡Hola! 🌿 Me encantaría saber cómo estás hoy.",
    "Hola 😊 ¿Cómo te sientes en este momento? Espero que todo esté bien.",
    "Hey 🌸 Solo quería enviarte un saludo y desearte un día tranquilo.",
    "Hola 💬 ¿Cómo va tu semana? Espero que con buena energía.",
    "¡Hola! 🌼 Me alegra tener noticias tuyas de nuevo. ¿Cómo estás?",
    "Hola 🌿 Espero que estés teniendo un momento de calma hoy.",
    "Hey ☀️ Hace un rato que no hablamos, ¿cómo estás llevando estos días?",
    "Hola 🌻 Espero que estés bien y rodeado de cosas buenas.",
    "¡Hola! 🌈 Me gustaría saber cómo te encuentras últimamente.",
    "Hola 💫 Espero que hoy encuentres un momento de paz para ti.",
    "Hey 🌷 ¿Cómo estás? Me encantaría saber de ti.",
    "Hola 😊 Solo paso a saludarte y recordarte que estoy aquí si me necesitas.",
    "¡Hola! 🌞 ¿Cómo te ha tratado la semana?",
    "Hola 🌿 Espero que estés sonriendo hoy, aunque sea un poco.",
    "Hey 💬 Me alegra saludarte. ¿Cómo te va todo?",
    "Hola 🌻 Hace un tiempo no hablamos, ¿cómo te encuentras?",
    "¡Hola! ✨ Espero que hoy te sientas en calma.",
    "Hola 🌸 Solo quería saber cómo estás y enviarte buena energía.",
    "Hey 🌞 ¿Qué tal tu día? Espero que estés bien.",
    "Hola 💫 Espero que todo marche bien contigo últimamente.",
    "¡Hola! 🌼 ¿Cómo te ha ido estos días?",
    "Hola 🌈 Me gustaría saber cómo te sientes hoy.",
    "Hey 🌿 ¿Cómo va todo por tu parte? Espero que estés bien.",
    "Hola 💬 Quiero saber cómo te encuentras y cómo te ha ido últimamente.",
    "¡Hola! 🌸 Espero que hoy tengas motivos para sonreír.",
    "Hola 🌞 ¿Cómo amaneciste hoy? Espero que con buena energía.",
    "Hey ✨ Solo paso a saludarte y desearte un bonito día.",
    "Hola 🌿 ¿Cómo te va? Hace un rato que no sé de ti.",
    "¡Hola! 🌻 Espero que te encuentres tranquilo y bien.",
    "Hola 😊 ¿Cómo estás hoy? Estoy aquí si quieres conversar.",
    "Hey 🌸 Me alegra escribirte de nuevo. ¿Cómo te sientes?",
    "Hola 💫 Espero que hoy estés rodeado de cosas buenas.",
    "¡Hola! 🌷 ¿Cómo ha estado todo por allá?",
    "Hola 🌿 Me gustaría saber cómo te sientes hoy.",
    "Hey ☀️ Espero que estés teniendo un día agradable.",
    "Hola 🌈 Hace un tiempo no sé de ti, ¿cómo va todo?",
    "¡Hola! 🌼 ¿Cómo ha ido tu semana hasta ahora?",
    "Hola 💭 Solo paso a saludarte y desearte bienestar.",
    "Hey 🌻 ¿Cómo va tu día? Espero que con serenidad.",
    "Hola 🌞 Me alegra saludarte. ¿Cómo estás hoy?",
    "¡Hola! 🌿 Espero que tu semana esté siendo tranquila.",
    "Hola 😊 ¿Qué tal te sientes hoy?",
    "Hey 🌸 ¿Cómo van las cosas contigo últimamente?",
    "Hola 💫 Espero que hoy tengas un momento para ti mismo.",
    "¡Hola! 🌻 ¿Cómo ha estado tu día?",
    "Hola 🌷 Hace un rato que no hablamos, ¿todo bien?",
    "Hey ☀️ Espero que estés en calma y con buena energía.",
    "Hola 🌿 ¿Cómo te encuentras en este momento?",
    "¡Hola! 🌈 Solo quería enviarte un saludo y buenos deseos.",
    "Hola 💬 Espero que esta semana te haya traído cosas buenas.",
    "Hey 🌸 Me encantaría saber cómo estás.",
    "Hola 🌞 ¿Cómo te va últimamente?",
    "¡Hola! 🌼 Espero que hoy sea un buen día para ti.",
    "Hola 🌿 ¿Todo bien contigo? Me alegra saludarte.",
    "Hey 🌻 Hace un tiempo no sé de ti, ¿cómo estás?",
    "Hola 💫 Espero que hoy encuentres un momento para descansar.",
    "¡Hola! 🌷 Me alegra poder escribirte, ¿cómo estás?",
    "Hola 🌈 Espero que estés bien y cuidándote mucho.",
    "Hey 🌿 ¿Cómo te sientes en estos días?",
    "Hola 💭 Solo quería saludarte y desearte tranquilidad.",
    "¡Hola! 🌸 Espero que todo esté marchando bien contigo.",
    "Hola 🌞 ¿Cómo te ha tratado el día de hoy?",
    "Hey 🌼 Espero que estés bien y con buena energía.",
    "Hola 🌿 Me alegra saludarte. ¿Cómo te encuentras hoy?",
    "¡Hola! 🌻 Espero que esta semana te traiga calma y alegría.",
    "Hola 😊 ¿Cómo ha estado tu ánimo últimamente?",
    "Hey 🌸 Solo quería enviarte un saludo lleno de buena vibra.",
    "Hola 💫 ¿Qué tal tu día? Espero que tranquilo.",
    "¡Hola! 🌷 Me encantaría saber cómo te va.",
    "Hola 🌞 Espero que hoy te sientas ligero y en paz.",
    "Hey 🌿 Hace un rato que no hablamos, ¿cómo va todo?",
    "Hola 🌻 Espero que estés bien y que tu día vaya mejorando.",
    "¡Hola! 🌈 Solo paso a saludarte y saber de ti.",
    "Hola 💬 ¿Cómo te encuentras hoy? Espero que bien.",
    "Hey 🌸 Me alegra escribirte otra vez. ¿Cómo va todo?",
    "Hola 🌞 Espero que tu semana esté yendo bien.",
    "¡Hola! 🌼 ¿Cómo te ha tratado la vida últimamente?",
    "Hola 🌿 Me alegra poder saludarte, ¿cómo estás?",
    "Hey ☀️ Espero que hoy te regales un momento de calma.",
    "Hola 🌻 Hace un tiempo no sé de ti, ¿cómo te sientes?",
    "¡Hola! 🌷 Espero que estés bien y rodeado de cosas bonitas.",
    "Hola 💫 Me alegra saludarte. ¿Cómo te ha ido?",
    "Hey 🌿 Solo quería recordarte que estoy aquí si me necesitas.",
    "Hola 🌞 ¿Cómo va todo por tu parte?",
    "¡Hola! 🌼 Espero que hoy te sientas motivado y tranquilo.",
    "Hola 🌸 ¿Cómo te encuentras? Me encantaría saber de ti."
];
module.exports = { mensajesSeguimiento };